language: python
python:
- 3.6.4
cache: pip
install:
- pip install -r requirements.txt
script:
- python foodExpenses.py
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
